from .categoryList import CategoryList
from .categoryDetail import CategoryDetail
from .productList import ProductList
from .productDetail import ProductDetail
from .customerList import CustomerList
from .customerDetail import CustomerDetail
from .orderList import OrderList
from .orderDetail import OrderDetail
from .customerLogin import customer_login
from .customerRegister import customer_register
from .customerOrder import customer_order
from .contactsDetail import ContactsDetail
