# Generated by Django 4.2.1 on 2023-06-15 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'Адрес пользователя', 'verbose_name_plural': 'Адреса пользователей'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AlterModelOptions(
            name='photosforproduct',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name': 'Рейтинг продукта', 'verbose_name_plural': 'Рейтинг продуктов'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name_for_site',
            field=models.CharField(default='', max_length=50, verbose_name='Название для сайта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='photosforproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_imgs', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fitting_sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='fitting', to='shop.size', verbose_name='Размеры на примерке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_colors', to='shop.color', verbose_name='Другие цвета'),
        ),
    ]
