# Generated by Django 4.2.1 on 2023-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_options_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(unique=True, verbose_name='Телефон'),
        ),
    ]
