# Generated by Django 4.2.1 on 2023-07-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosforproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_imgs', to='shop.product', unique=True, verbose_name='Товар'),
        ),
    ]
