# Generated by Django 4.2.1 on 2025-08-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_mobile'),
        ('shop', '0008_alter_photosforproduct_product'),
    ]

    operations = [
    ]
