# Generated by Django 4.2.1 on 2025-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='LandingSlide',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_wa',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
