# Generated by Django 4.2.1 on 2025-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_customeraddress_customer_delete_landingslide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=150, verbose_name='Адрес'),
        ),
    ]
