# Generated by Django 4.2.1 on 2025-08-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=150, verbose_name='Адрес'),
        ),
    ]
